POST http://localhost:3000/User
Content-Type: application/json

{
    "name": "Gordon Ramsay",
    "email": "gordon@cooking.com",
    "password": "lambSauce",
    "isChef": true
}

###
GET http://localhost:3000/User

###
POST http://localhost:3000/User/login
Content-Type: application/json

{
    "email": "gordon@cooking.com",
    "password": "lambSauce"
}

###
POST http://localhost:3000/User/logout

###
POST http://localhost:3000/Ingredient
Content-Type: application/json

{
    "name": "Mushroomasda",
    "category": "NotShrooms",
    "budget": "Cheap"
}

###
GET http://localhost:3000/Ingredient